### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by saraedum** [MCLF/henselization#17]
[#22956](https://trac.sagemath.org/ticket/22956) collects a few performance issues:

**TODO**:
* [ ] Fix [#23170](https://trac.sagemath.org/ticket/23170)
* [ ] Fix [#23171](https://trac.sagemath.org/ticket/23171)
* [ ] Fix [#23173](https://trac.sagemath.org/ticket/23173)

**Comment by saraedum** [comment]
It's probably not worth it to monkey patch these.
